Вторая часть диплома
Piroggard/java-explore-with-me pull request #2
Opened 2023-12-09 10:48 UTC by Piroggard

2023-12-10 19:35 UTC, sergeymamonov requested changes
Не исправлены замечания в ревью первой части диплома.
Проверьте форматирование во всех сущностях и объектаъ dto.
Где встречается from / size, там может быть деление на ноль.

2023-12-10 19:35 UTC, sergeymamonov commented on pom.xml
> +	<dependencies>
Указывать зависимости в родительском помнике не очень хорошая практика. Лучше указывать все зависимости в дочерних помниках. Пример, нужна зависимость для каждого из подмодулей, но в одном нужна версия 1, а во втором версия 2. Если указывать зависимость в дочерних помниках, то легко указать в одном одну версию, а во втором другую версию. В крайнем случае размещать зависимости в dependencyManagement

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/Dockerfile
> +#ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
Закомментированного кода быть не должно.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/resources/schema.sql
> +--   confirmed_requests  BIGINT,
Закомментированного кода быть не должно.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/category/dto/CategoryDto.java
> +     Long id;
Форматирование.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/category/service/CategoryServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size);
Здесь может быть деление на ноль.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/category/Category.java
> +     Long id;
Форматирование.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/compilation/CompilationRepository.java
> +    List<Compilation> findAllByPinned(Boolean pinned, Pageable pageable);
Метод где-то используется в проекте?

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/controllers/PublicEventController.java
> +            if (start.isAfter(end)) {
В данном случае можно написать один if с условиями из первого и второго if.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/repositories/EventCriteriaRepositoryImpl.java
> +                    LocalDateTime.now().plusYears(100)));
Число нужно вынести в константу с информативным названием.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/repositories/EventRepository.java
> +    Optional<Event> findByIdAndState(Long eventId, EventState eventState);
Метод где-то вызывается в проекте?

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/search/Sort.java
> +public enum Sort {
Класс где-то используется в проекте?

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +            throw new ConflictException(String.format("Дата события не может быть ранее даты добавления на 1 час", 1));
Пропущен оператор %.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                throw new ConflictException(String.format("Дата события не может быть ранее даты добавления на 1 час", 1));
Пропущен оператор %.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                throw new ConflictException(String.format("Событие не может быть ранее, " +
Пропущен оператор %.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                            String.format("Дата события должна быть не ранее, чем за час до публикации", 1));
Пропущен оператор %.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                .peek(eventDto -> eventDto.setViews(this.getViews(eventDto.getId())))
Метод getViews выполняются запросы к БД, а значит здесь выполняются запросы к БД в цикле.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                        .setViews(this.getViews(eventDtos.getId())))
Запросы к БД в цикле.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +    private Event getEvent(Long eventId, Long userId) {
Метод где-то вызывается?

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +    private void setConfirmedRequests(List<EventDto> events) {
Метод где-то вызывается?

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +    private String serviceName;
Пропущен модификатор final.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +            event.setConfirmedRequests(requestRepository.countByEventIdAndConfirmed(event.getId()));
Запросы к БД в цикле.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +            throw new ConflictException("Нельзя обновить опубликованное событие");
Лучше вызвать equals у константы, чтобы не получить NPE. То есть PUBLISHED.equals(eventToUpd.getState()). Посмотрите остальные места, где вызывается метод equals.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/request/dto/RequestMapper.java
> +    public Request toRequestFromUserIdAndEventId(Long userId, Long eventId) {
Метод где-то вызывается в проекте?

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/request/RequestRepository.java
> +    Integer countByEventId(@Param(value = "eventId") Long eventId);
Метод где-то вызывается в проекте?

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/util/ErrorResponse.java
> +    public ErrorResponse(String error) {
Геттер и конструктор лучше заменить аннотациями Ломбок.

2023-12-10 19:35 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/util/ServiceMainErrorHandler.java
> +}
Добавить обработку 500 ошибки.

2023-12-11 15:26 UTC, Piroggard commented on service-main/Dockerfile
> +#ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
Исправлено

2023-12-11 15:27 UTC, Piroggard commented on service-main/src/main/resources/schema.sql
> +--   confirmed_requests  BIGINT,
Исправлено

2023-12-11 15:30 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/category/dto/CategoryDto.java
> +     Long id;
Исправлено

2023-12-11 15:33 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/category/Category.java
> +     Long id;
Исправлено

2023-12-11 15:51 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/compilation/CompilationRepository.java
> +    List<Compilation> findAllByPinned(Boolean pinned, Pageable pageable);
Исправлено

2023-12-11 15:53 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/repositories/EventRepository.java
> +    Optional<Event> findByIdAndState(Long eventId, EventState eventState);
Исправлено

2023-12-11 15:58 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/search/Sort.java
> +public enum Sort {
Исправлено

2023-12-13 18:20 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/controllers/PublicEventController.java
> +            if (start.isAfter(end)) {
Исправлено

2023-12-13 18:44 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/repositories/EventCriteriaRepositoryImpl.java
> +                    LocalDateTime.now().plusYears(100)));
Исправлено

2023-12-13 18:52 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +    private Event getEvent(Long eventId, Long userId) {
Исправлено

2023-12-13 18:52 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +    private void setConfirmedRequests(List<EventDto> events) {
Исправлено

2023-12-15 14:21 UTC, Piroggard commented on pom.xml
> +	<dependencies>
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/category/service/CategoryServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size);
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +            throw new ConflictException(String.format("Дата события не может быть ранее даты добавления на 1 час", 1));
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                throw new ConflictException(String.format("Дата события не может быть ранее даты добавления на 1 час", 1));
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                throw new ConflictException(String.format("Событие не может быть ранее, " +
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                            String.format("Дата события должна быть не ранее, чем за час до публикации", 1));
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                .peek(eventDto -> eventDto.setViews(this.getViews(eventDto.getId())))
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                        .setViews(this.getViews(eventDtos.getId())))
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +    private String serviceName;
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +            event.setConfirmedRequests(requestRepository.countByEventIdAndConfirmed(event.getId()));
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +            throw new ConflictException("Нельзя обновить опубликованное событие");
Исправлено

2023-12-15 14:22 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/request/dto/RequestMapper.java
> +    public Request toRequestFromUserIdAndEventId(Long userId, Long eventId) {
Исправлено

2023-12-15 14:23 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/request/RequestRepository.java
> +    Integer countByEventId(@Param(value = "eventId") Long eventId);
Исправлено

2023-12-15 14:23 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/util/ErrorResponse.java
> +    public ErrorResponse(String error) {
Исправлено

2023-12-15 14:23 UTC, Piroggard commented on service-main/src/main/java/ru/practicum/explore/util/ServiceMainErrorHandler.java
> +}
Исправлено

2023-12-17 04:27 UTC, sergeymamonov approved these changes

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/controllers/PublicEventController.java
> +        if (rangeStart != null) {
Я бы перенес всю эту логику и валидацию в сервис.

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/repositories/EventCriteriaRepositoryImpl.java
> +    private final int oneHundredYearsLater = 100;
Для костант используются заглавные буквы. Плюс название не информативное. В названии нужно передать смысл, этого числа. Например, MAX_YEARS_FOR_SHOW_EVENTS

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                throw new ConflictException(String.format("Событие не может быть ранее, " +
В этом месте не исправлено.

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +            if (rangeEndTime.isBefore(rangeStartTime)) {
Можно объединить ифы.

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +        events.stream()
Результат вычисления стрима никуда не сохраняется.

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +            if (rangeEndTime.isBefore(rangeStartTime)) {
Можно объединить ифы.

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +        LocalDateTime startViewsDate = LocalDateTime.of(1970, Month.JANUARY, 1, 0, 0);
Лучше вынести в константу.

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +        eventFullDto.setViews(getViews(event));
Вообще это не очень хорошо делать в транзакционном метод запрос к БД и рест запрос. Рест запрос может быть медленным. А транзакция держит коннект к БД, пока не пройдет рест запрос. И можно все коннекты к базе таким образом использовать. То есть сделать БД недоступной.

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +        List<EventDto> resultEventDtos = new ArrayList<>(updatedEventDtos);
Можно сразу вернуть, без создания промежуточной переменной.

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                    Long confirmedRequests = this.getCountConfirmedRequestsByEvent(event);
Запросы к БД в цикле.

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +                .filter(request -> request.getStatus().equals(RequestStatus.CONFIRMED) ||
Лучше поменять местами RequestStatus.CONFIRMED.equals()

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +import java.util.*;
Лучше не использовать импорт через астериск.

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +    private final HashMap<Long, HashSet<String>> httpServletRequests = new HashMap<>();
Лучше использовать интерфейс private final Map<Long, HashSet<String>> ...

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/event/service/EventServiceImpl.java
> +    public EventServiceImpl(EventRepository eventRepository, LocationRepository locationRepository,
Попробуйте через @RequiredArgsConstructor

2023-12-17 04:27 UTC, sergeymamonov commented on service-main/src/main/java/ru/practicum/explore/util/ServiceMainErrorHandler.java
> +    @ExceptionHandler(UncheckedIOException.class)
обработка 500 ошибки это перехват и NPE и других ошибок, поэтому UncheckedIOException нужно удалить.

2023-12-21 14:23 UTC, merged